[project]
name = "tpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "word2number>=1.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
